// Code generated by protoc-gen-go.
// source: agent/report/agent.proto
// DO NOT EDIT!

/*
Package report is a generated protocol buffer package.

It is generated from these files:
	agent/report/agent.proto
	agent/report/config.proto
	agent/report/host.proto
	agent/report/network.proto
	agent/report/process.proto
	agent/report/report.proto

It has these top-level messages:
	Agent
	Config
	Host
	NetWork
	Process
	Reply
	ReplyMCSD
	ReplyRT
	Report
	MCSD
	ProcessRT
*/
package report

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Agent struct {
	InstallTime string `protobuf:"bytes,1,opt,name=InstallTime" json:"InstallTime,omitempty"`
	Version     string `protobuf:"bytes,2,opt,name=Version" json:"Version,omitempty"`
}

func (m *Agent) Reset()                    { *m = Agent{} }
func (m *Agent) String() string            { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()               {}
func (*Agent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*Agent)(nil), "report.Agent")
}

func init() { proto.RegisterFile("agent/report/agent.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 103 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x48, 0x4c, 0x4f, 0xcd,
	0x2b, 0xd1, 0x2f, 0x4a, 0x2d, 0xc8, 0x2f, 0x2a, 0xd1, 0x07, 0x73, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b,
	0xf2, 0x85, 0xd8, 0x20, 0x62, 0x4a, 0xce, 0x5c, 0xac, 0x8e, 0x20, 0x61, 0x21, 0x05, 0x2e, 0x6e,
	0xcf, 0xbc, 0xe2, 0x92, 0xc4, 0x9c, 0x9c, 0x90, 0xcc, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0xce, 0x20, 0x64, 0x21, 0x21, 0x09, 0x2e, 0xf6, 0xb0, 0xd4, 0xa2, 0xe2, 0xcc, 0xfc, 0x3c, 0x09,
	0x26, 0xb0, 0x2c, 0x8c, 0x9b, 0xc4, 0x06, 0x36, 0xd3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x28,
	0xd9, 0x34, 0xa9, 0x6f, 0x00, 0x00, 0x00,
}
